# Generated by Django 3.1.1 on 2020-09-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20200920_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.genre'),
        ),
    ]
