# Generated by Django 3.1.1 on 2020-09-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20200920_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='genre',
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='docs.Tag'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
