# Generated by Django 3.1.1 on 2020-09-22 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20200922_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.artist'),
        ),
    ]
