# Generated by Django 3.1.1 on 2020-09-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_document_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
