# Generated by Django 3.1.1 on 2020-09-22 22:44

from django.db import migrations, models
import docs.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_auto_20200922_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=docs.models.file_upload_path),
        ),
    ]
