# Generated by Django 3.1.1 on 2020-09-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_auto_20200922_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
